// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketattachment"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketAttachment is the model entity for the SupportTicketAttachment schema.
type SupportTicketAttachment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID int64 `json:"message_id,omitempty"`
	// UploaderID holds the value of the "uploader_id" field.
	UploaderID int64 `json:"uploader_id,omitempty"`
	// ObjectKey holds the value of the "object_key" field.
	ObjectKey string `json:"object_key,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupportTicketAttachmentQuery when eager-loading is set.
	Edges        SupportTicketAttachmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupportTicketAttachmentEdges holds the relations/edges for other nodes in the graph.
type SupportTicketAttachmentEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *SupportTicket `json:"ticket,omitempty"`
	// Message holds the value of the message edge.
	Message *SupportTicketMessage `json:"message,omitempty"`
	// Uploader holds the value of the uploader edge.
	Uploader *User `json:"uploader,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketAttachmentEdges) TicketOrErr() (*SupportTicket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supportticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// MessageOrErr returns the Message value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketAttachmentEdges) MessageOrErr() (*SupportTicketMessage, error) {
	if e.Message != nil {
		return e.Message, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: supportticketmessage.Label}
	}
	return nil, &NotLoadedError{edge: "message"}
}

// UploaderOrErr returns the Uploader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupportTicketAttachmentEdges) UploaderOrErr() (*User, error) {
	if e.Uploader != nil {
		return e.Uploader, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploader"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupportTicketAttachment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supportticketattachment.FieldID, supportticketattachment.FieldTicketID, supportticketattachment.FieldMessageID, supportticketattachment.FieldUploaderID, supportticketattachment.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case supportticketattachment.FieldObjectKey, supportticketattachment.FieldFileName, supportticketattachment.FieldContentType:
			values[i] = new(sql.NullString)
		case supportticketattachment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupportTicketAttachment fields.
func (_m *SupportTicketAttachment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supportticketattachment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supportticketattachment.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case supportticketattachment.FieldMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.Int64
			}
		case supportticketattachment.FieldUploaderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploader_id", values[i])
			} else if value.Valid {
				_m.UploaderID = value.Int64
			}
		case supportticketattachment.FieldObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_key", values[i])
			} else if value.Valid {
				_m.ObjectKey = value.String
			}
		case supportticketattachment.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = value.String
			}
		case supportticketattachment.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case supportticketattachment.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case supportticketattachment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupportTicketAttachment.
// This includes values selected through modifiers, order, etc.
func (_m *SupportTicketAttachment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the SupportTicketAttachment entity.
func (_m *SupportTicketAttachment) QueryTicket() *SupportTicketQuery {
	return NewSupportTicketAttachmentClient(_m.config).QueryTicket(_m)
}

// QueryMessage queries the "message" edge of the SupportTicketAttachment entity.
func (_m *SupportTicketAttachment) QueryMessage() *SupportTicketMessageQuery {
	return NewSupportTicketAttachmentClient(_m.config).QueryMessage(_m)
}

// QueryUploader queries the "uploader" edge of the SupportTicketAttachment entity.
func (_m *SupportTicketAttachment) QueryUploader() *UserQuery {
	return NewSupportTicketAttachmentClient(_m.config).QueryUploader(_m)
}

// Update returns a builder for updating this SupportTicketAttachment.
// Note that you need to call SupportTicketAttachment.Unwrap() before calling this method if this SupportTicketAttachment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupportTicketAttachment) Update() *SupportTicketAttachmentUpdateOne {
	return NewSupportTicketAttachmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupportTicketAttachment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupportTicketAttachment) Unwrap() *SupportTicketAttachment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupportTicketAttachment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupportTicketAttachment) String() string {
	var builder strings.Builder
	builder.WriteString("SupportTicketAttachment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageID))
	builder.WriteString(", ")
	builder.WriteString("uploader_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploaderID))
	builder.WriteString(", ")
	builder.WriteString("object_key=")
	builder.WriteString(_m.ObjectKey)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(_m.FileName)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupportTicketAttachments is a parsable slice of SupportTicketAttachment.
type SupportTicketAttachments []*SupportTicketAttachment
