// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/ticketmessage"
)

// TicketMessageUpdate is the builder for updating TicketMessage entities.
type TicketMessageUpdate struct {
	config
	hooks    []Hook
	mutation *TicketMessageMutation
}

// Where appends a list predicates to the TicketMessageUpdate builder.
func (_u *TicketMessageUpdate) Where(ps ...predicate.TicketMessage) *TicketMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSenderRole sets the "sender_role" field.
func (_u *TicketMessageUpdate) SetSenderRole(v string) *TicketMessageUpdate {
	_u.mutation.SetSenderRole(v)
	return _u
}

// SetNillableSenderRole sets the "sender_role" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableSenderRole(v *string) *TicketMessageUpdate {
	if v != nil {
		_u.SetSenderRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *TicketMessageUpdate) SetContent(v string) *TicketMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *TicketMessageUpdate) SetNillableContent(v *string) *TicketMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_u *TicketMessageUpdate) Mutation() *TicketMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketMessageUpdate) check() error {
	if v, ok := _u.mutation.SenderRole(); ok {
		if err := ticketmessage.SenderRoleValidator(v); err != nil {
			return &ValidationError{Name: "sender_role", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.sender_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := ticketmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.content": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.ticket"`)
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.sender"`)
	}
	return nil
}

func (_u *TicketMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketmessage.Table, ticketmessage.Columns, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderRole(); ok {
		_spec.SetField(ticketmessage.FieldSenderRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ticketmessage.FieldContent, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketMessageUpdateOne is the builder for updating a single TicketMessage entity.
type TicketMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketMessageMutation
}

// SetSenderRole sets the "sender_role" field.
func (_u *TicketMessageUpdateOne) SetSenderRole(v string) *TicketMessageUpdateOne {
	_u.mutation.SetSenderRole(v)
	return _u
}

// SetNillableSenderRole sets the "sender_role" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableSenderRole(v *string) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetSenderRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *TicketMessageUpdateOne) SetContent(v string) *TicketMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *TicketMessageUpdateOne) SetNillableContent(v *string) *TicketMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// Mutation returns the TicketMessageMutation object of the builder.
func (_u *TicketMessageUpdateOne) Mutation() *TicketMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the TicketMessageUpdate builder.
func (_u *TicketMessageUpdateOne) Where(ps ...predicate.TicketMessage) *TicketMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketMessageUpdateOne) Select(field string, fields ...string) *TicketMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TicketMessage entity.
func (_u *TicketMessageUpdateOne) Save(ctx context.Context) (*TicketMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketMessageUpdateOne) SaveX(ctx context.Context) *TicketMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SenderRole(); ok {
		if err := ticketmessage.SenderRoleValidator(v); err != nil {
			return &ValidationError{Name: "sender_role", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.sender_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := ticketmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "TicketMessage.content": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.ticket"`)
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TicketMessage.sender"`)
	}
	return nil
}

func (_u *TicketMessageUpdateOne) sqlSave(ctx context.Context) (_node *TicketMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticketmessage.Table, ticketmessage.Columns, sqlgraph.NewFieldSpec(ticketmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TicketMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticketmessage.FieldID)
		for _, f := range fields {
			if !ticketmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticketmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderRole(); ok {
		_spec.SetField(ticketmessage.FieldSenderRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ticketmessage.FieldContent, field.TypeString, value)
	}
	_node = &TicketMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
