// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamprovider"
)

// UpstreamProviderUpdate is the builder for updating UpstreamProvider entities.
type UpstreamProviderUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamProviderMutation
}

// Where appends a list predicates to the UpstreamProviderUpdate builder.
func (_u *UpstreamProviderUpdate) Where(ps ...predicate.UpstreamProvider) *UpstreamProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamProviderUpdate) SetUpdatedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamProviderUpdate) SetDeletedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableDeletedAt(v *time.Time) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamProviderUpdate) ClearDeletedAt() *UpstreamProviderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamProviderUpdate) SetName(v string) *UpstreamProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableName(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamProviderUpdate) SetBaseURL(v string) *UpstreamProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableBaseURL(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UpstreamProviderUpdate) SetNotes(v string) *UpstreamProviderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableNotes(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UpstreamProviderUpdate) ClearNotes() *UpstreamProviderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUsername sets the "username" field.
func (_u *UpstreamProviderUpdate) SetUsername(v string) *UpstreamProviderUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableUsername(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *UpstreamProviderUpdate) SetPasswordEncrypted(v string) *UpstreamProviderUpdate {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillablePasswordEncrypted(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetTotpSecretEncrypted sets the "totp_secret_encrypted" field.
func (_u *UpstreamProviderUpdate) SetTotpSecretEncrypted(v string) *UpstreamProviderUpdate {
	_u.mutation.SetTotpSecretEncrypted(v)
	return _u
}

// SetNillableTotpSecretEncrypted sets the "totp_secret_encrypted" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableTotpSecretEncrypted(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetTotpSecretEncrypted(*v)
	}
	return _u
}

// ClearTotpSecretEncrypted clears the value of the "totp_secret_encrypted" field.
func (_u *UpstreamProviderUpdate) ClearTotpSecretEncrypted() *UpstreamProviderUpdate {
	_u.mutation.ClearTotpSecretEncrypted()
	return _u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_u *UpstreamProviderUpdate) SetTokenEncrypted(v string) *UpstreamProviderUpdate {
	_u.mutation.SetTokenEncrypted(v)
	return _u
}

// SetNillableTokenEncrypted sets the "token_encrypted" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableTokenEncrypted(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetTokenEncrypted(*v)
	}
	return _u
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (_u *UpstreamProviderUpdate) ClearTokenEncrypted() *UpstreamProviderUpdate {
	_u.mutation.ClearTokenEncrypted()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UpstreamProviderUpdate) SetTokenExpiresAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableTokenExpiresAt(v *time.Time) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UpstreamProviderUpdate) ClearTokenExpiresAt() *UpstreamProviderUpdate {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UpstreamProviderUpdate) SetBalance(v float64) *UpstreamProviderUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableBalance(v *float64) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UpstreamProviderUpdate) AddBalance(v float64) *UpstreamProviderUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *UpstreamProviderUpdate) ClearBalance() *UpstreamProviderUpdate {
	_u.mutation.ClearBalance()
	return _u
}

// SetFrozenBalance sets the "frozen_balance" field.
func (_u *UpstreamProviderUpdate) SetFrozenBalance(v float64) *UpstreamProviderUpdate {
	_u.mutation.ResetFrozenBalance()
	_u.mutation.SetFrozenBalance(v)
	return _u
}

// SetNillableFrozenBalance sets the "frozen_balance" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableFrozenBalance(v *float64) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetFrozenBalance(*v)
	}
	return _u
}

// AddFrozenBalance adds value to the "frozen_balance" field.
func (_u *UpstreamProviderUpdate) AddFrozenBalance(v float64) *UpstreamProviderUpdate {
	_u.mutation.AddFrozenBalance(v)
	return _u
}

// ClearFrozenBalance clears the value of the "frozen_balance" field.
func (_u *UpstreamProviderUpdate) ClearFrozenBalance() *UpstreamProviderUpdate {
	_u.mutation.ClearFrozenBalance()
	return _u
}

// SetUpstreamConcurrency sets the "upstream_concurrency" field.
func (_u *UpstreamProviderUpdate) SetUpstreamConcurrency(v int) *UpstreamProviderUpdate {
	_u.mutation.ResetUpstreamConcurrency()
	_u.mutation.SetUpstreamConcurrency(v)
	return _u
}

// SetNillableUpstreamConcurrency sets the "upstream_concurrency" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableUpstreamConcurrency(v *int) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetUpstreamConcurrency(*v)
	}
	return _u
}

// AddUpstreamConcurrency adds value to the "upstream_concurrency" field.
func (_u *UpstreamProviderUpdate) AddUpstreamConcurrency(v int) *UpstreamProviderUpdate {
	_u.mutation.AddUpstreamConcurrency(v)
	return _u
}

// ClearUpstreamConcurrency clears the value of the "upstream_concurrency" field.
func (_u *UpstreamProviderUpdate) ClearUpstreamConcurrency() *UpstreamProviderUpdate {
	_u.mutation.ClearUpstreamConcurrency()
	return _u
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (_u *UpstreamProviderUpdate) SetUpstreamUserID(v string) *UpstreamProviderUpdate {
	_u.mutation.SetUpstreamUserID(v)
	return _u
}

// SetNillableUpstreamUserID sets the "upstream_user_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableUpstreamUserID(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetUpstreamUserID(*v)
	}
	return _u
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (_u *UpstreamProviderUpdate) ClearUpstreamUserID() *UpstreamProviderUpdate {
	_u.mutation.ClearUpstreamUserID()
	return _u
}

// SetRateCorrection sets the "rate_correction" field.
func (_u *UpstreamProviderUpdate) SetRateCorrection(v float64) *UpstreamProviderUpdate {
	_u.mutation.ResetRateCorrection()
	_u.mutation.SetRateCorrection(v)
	return _u
}

// SetNillableRateCorrection sets the "rate_correction" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableRateCorrection(v *float64) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetRateCorrection(*v)
	}
	return _u
}

// AddRateCorrection adds value to the "rate_correction" field.
func (_u *UpstreamProviderUpdate) AddRateCorrection(v float64) *UpstreamProviderUpdate {
	_u.mutation.AddRateCorrection(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamProviderUpdate) SetStatus(v string) *UpstreamProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableStatus(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *UpstreamProviderUpdate) SetLastSyncAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableLastSyncAt(v *time.Time) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *UpstreamProviderUpdate) ClearLastSyncAt() *UpstreamProviderUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *UpstreamProviderUpdate) SetLastSyncError(v string) *UpstreamProviderUpdate {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableLastSyncError(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *UpstreamProviderUpdate) ClearLastSyncError() *UpstreamProviderUpdate {
	_u.mutation.ClearLastSyncError()
	return _u
}

// SetSyncEnabled sets the "sync_enabled" field.
func (_u *UpstreamProviderUpdate) SetSyncEnabled(v bool) *UpstreamProviderUpdate {
	_u.mutation.SetSyncEnabled(v)
	return _u
}

// SetNillableSyncEnabled sets the "sync_enabled" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableSyncEnabled(v *bool) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetSyncEnabled(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the UpstreamGroup entity by IDs.
func (_u *UpstreamProviderUpdate) AddGroupIDs(ids ...int64) *UpstreamProviderUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamProviderUpdate) AddGroups(v ...*UpstreamGroup) *UpstreamProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *UpstreamProviderUpdate) AddAccountIDs(ids ...int64) *UpstreamProviderUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *UpstreamProviderUpdate) AddAccounts(v ...*Account) *UpstreamProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_u *UpstreamProviderUpdate) Mutation() *UpstreamProviderMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamProviderUpdate) ClearGroups() *UpstreamProviderUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to UpstreamGroup entities by IDs.
func (_u *UpstreamProviderUpdate) RemoveGroupIDs(ids ...int64) *UpstreamProviderUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to UpstreamGroup entities.
func (_u *UpstreamProviderUpdate) RemoveGroups(v ...*UpstreamGroup) *UpstreamProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *UpstreamProviderUpdate) ClearAccounts() *UpstreamProviderUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *UpstreamProviderUpdate) RemoveAccountIDs(ids ...int64) *UpstreamProviderUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *UpstreamProviderUpdate) RemoveAccounts(v ...*Account) *UpstreamProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamProviderUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamProviderUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstreamprovider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamprovider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := upstreamprovider.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamUserID(); ok {
		if err := upstreamprovider.UpstreamUserIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_user_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.upstream_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamprovider.Table, upstreamprovider.Columns, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(upstreamprovider.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(upstreamprovider.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(upstreamprovider.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(upstreamprovider.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotpSecretEncrypted(); ok {
		_spec.SetField(upstreamprovider.FieldTotpSecretEncrypted, field.TypeString, value)
	}
	if _u.mutation.TotpSecretEncryptedCleared() {
		_spec.ClearField(upstreamprovider.FieldTotpSecretEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenEncrypted(); ok {
		_spec.SetField(upstreamprovider.FieldTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.TokenEncryptedCleared() {
		_spec.ClearField(upstreamprovider.FieldTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstreamprovider.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(upstreamprovider.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(upstreamprovider.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(upstreamprovider.FieldBalance, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(upstreamprovider.FieldBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FrozenBalance(); ok {
		_spec.SetField(upstreamprovider.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBalance(); ok {
		_spec.AddField(upstreamprovider.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if _u.mutation.FrozenBalanceCleared() {
		_spec.ClearField(upstreamprovider.FieldFrozenBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamConcurrency(); ok {
		_spec.SetField(upstreamprovider.FieldUpstreamConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpstreamConcurrency(); ok {
		_spec.AddField(upstreamprovider.FieldUpstreamConcurrency, field.TypeInt, value)
	}
	if _u.mutation.UpstreamConcurrencyCleared() {
		_spec.ClearField(upstreamprovider.FieldUpstreamConcurrency, field.TypeInt)
	}
	if value, ok := _u.mutation.UpstreamUserID(); ok {
		_spec.SetField(upstreamprovider.FieldUpstreamUserID, field.TypeString, value)
	}
	if _u.mutation.UpstreamUserIDCleared() {
		_spec.ClearField(upstreamprovider.FieldUpstreamUserID, field.TypeString)
	}
	if value, ok := _u.mutation.RateCorrection(); ok {
		_spec.SetField(upstreamprovider.FieldRateCorrection, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateCorrection(); ok {
		_spec.AddField(upstreamprovider.FieldRateCorrection, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(upstreamprovider.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(upstreamprovider.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(upstreamprovider.FieldLastSyncError, field.TypeString)
	}
	if value, ok := _u.mutation.SyncEnabled(); ok {
		_spec.SetField(upstreamprovider.FieldSyncEnabled, field.TypeBool, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.GroupsTable,
			Columns: []string{upstreamprovider.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.GroupsTable,
			Columns: []string{upstreamprovider.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.GroupsTable,
			Columns: []string{upstreamprovider.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.AccountsTable,
			Columns: []string{upstreamprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.AccountsTable,
			Columns: []string{upstreamprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.AccountsTable,
			Columns: []string{upstreamprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamProviderUpdateOne is the builder for updating a single UpstreamProvider entity.
type UpstreamProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamProviderUpdateOne) SetUpdatedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamProviderUpdateOne) SetDeletedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableDeletedAt(v *time.Time) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamProviderUpdateOne) ClearDeletedAt() *UpstreamProviderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamProviderUpdateOne) SetName(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableName(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamProviderUpdateOne) SetBaseURL(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableBaseURL(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UpstreamProviderUpdateOne) SetNotes(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableNotes(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UpstreamProviderUpdateOne) ClearNotes() *UpstreamProviderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUsername sets the "username" field.
func (_u *UpstreamProviderUpdateOne) SetUsername(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableUsername(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *UpstreamProviderUpdateOne) SetPasswordEncrypted(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillablePasswordEncrypted(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetTotpSecretEncrypted sets the "totp_secret_encrypted" field.
func (_u *UpstreamProviderUpdateOne) SetTotpSecretEncrypted(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetTotpSecretEncrypted(v)
	return _u
}

// SetNillableTotpSecretEncrypted sets the "totp_secret_encrypted" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableTotpSecretEncrypted(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetTotpSecretEncrypted(*v)
	}
	return _u
}

// ClearTotpSecretEncrypted clears the value of the "totp_secret_encrypted" field.
func (_u *UpstreamProviderUpdateOne) ClearTotpSecretEncrypted() *UpstreamProviderUpdateOne {
	_u.mutation.ClearTotpSecretEncrypted()
	return _u
}

// SetTokenEncrypted sets the "token_encrypted" field.
func (_u *UpstreamProviderUpdateOne) SetTokenEncrypted(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetTokenEncrypted(v)
	return _u
}

// SetNillableTokenEncrypted sets the "token_encrypted" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableTokenEncrypted(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetTokenEncrypted(*v)
	}
	return _u
}

// ClearTokenEncrypted clears the value of the "token_encrypted" field.
func (_u *UpstreamProviderUpdateOne) ClearTokenEncrypted() *UpstreamProviderUpdateOne {
	_u.mutation.ClearTokenEncrypted()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UpstreamProviderUpdateOne) SetTokenExpiresAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableTokenExpiresAt(v *time.Time) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UpstreamProviderUpdateOne) ClearTokenExpiresAt() *UpstreamProviderUpdateOne {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UpstreamProviderUpdateOne) SetBalance(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableBalance(v *float64) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UpstreamProviderUpdateOne) AddBalance(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *UpstreamProviderUpdateOne) ClearBalance() *UpstreamProviderUpdateOne {
	_u.mutation.ClearBalance()
	return _u
}

// SetFrozenBalance sets the "frozen_balance" field.
func (_u *UpstreamProviderUpdateOne) SetFrozenBalance(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.ResetFrozenBalance()
	_u.mutation.SetFrozenBalance(v)
	return _u
}

// SetNillableFrozenBalance sets the "frozen_balance" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableFrozenBalance(v *float64) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetFrozenBalance(*v)
	}
	return _u
}

// AddFrozenBalance adds value to the "frozen_balance" field.
func (_u *UpstreamProviderUpdateOne) AddFrozenBalance(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.AddFrozenBalance(v)
	return _u
}

// ClearFrozenBalance clears the value of the "frozen_balance" field.
func (_u *UpstreamProviderUpdateOne) ClearFrozenBalance() *UpstreamProviderUpdateOne {
	_u.mutation.ClearFrozenBalance()
	return _u
}

// SetUpstreamConcurrency sets the "upstream_concurrency" field.
func (_u *UpstreamProviderUpdateOne) SetUpstreamConcurrency(v int) *UpstreamProviderUpdateOne {
	_u.mutation.ResetUpstreamConcurrency()
	_u.mutation.SetUpstreamConcurrency(v)
	return _u
}

// SetNillableUpstreamConcurrency sets the "upstream_concurrency" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableUpstreamConcurrency(v *int) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetUpstreamConcurrency(*v)
	}
	return _u
}

// AddUpstreamConcurrency adds value to the "upstream_concurrency" field.
func (_u *UpstreamProviderUpdateOne) AddUpstreamConcurrency(v int) *UpstreamProviderUpdateOne {
	_u.mutation.AddUpstreamConcurrency(v)
	return _u
}

// ClearUpstreamConcurrency clears the value of the "upstream_concurrency" field.
func (_u *UpstreamProviderUpdateOne) ClearUpstreamConcurrency() *UpstreamProviderUpdateOne {
	_u.mutation.ClearUpstreamConcurrency()
	return _u
}

// SetUpstreamUserID sets the "upstream_user_id" field.
func (_u *UpstreamProviderUpdateOne) SetUpstreamUserID(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetUpstreamUserID(v)
	return _u
}

// SetNillableUpstreamUserID sets the "upstream_user_id" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableUpstreamUserID(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetUpstreamUserID(*v)
	}
	return _u
}

// ClearUpstreamUserID clears the value of the "upstream_user_id" field.
func (_u *UpstreamProviderUpdateOne) ClearUpstreamUserID() *UpstreamProviderUpdateOne {
	_u.mutation.ClearUpstreamUserID()
	return _u
}

// SetRateCorrection sets the "rate_correction" field.
func (_u *UpstreamProviderUpdateOne) SetRateCorrection(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.ResetRateCorrection()
	_u.mutation.SetRateCorrection(v)
	return _u
}

// SetNillableRateCorrection sets the "rate_correction" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableRateCorrection(v *float64) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetRateCorrection(*v)
	}
	return _u
}

// AddRateCorrection adds value to the "rate_correction" field.
func (_u *UpstreamProviderUpdateOne) AddRateCorrection(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.AddRateCorrection(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamProviderUpdateOne) SetStatus(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableStatus(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *UpstreamProviderUpdateOne) SetLastSyncAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableLastSyncAt(v *time.Time) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *UpstreamProviderUpdateOne) ClearLastSyncAt() *UpstreamProviderUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *UpstreamProviderUpdateOne) SetLastSyncError(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableLastSyncError(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *UpstreamProviderUpdateOne) ClearLastSyncError() *UpstreamProviderUpdateOne {
	_u.mutation.ClearLastSyncError()
	return _u
}

// SetSyncEnabled sets the "sync_enabled" field.
func (_u *UpstreamProviderUpdateOne) SetSyncEnabled(v bool) *UpstreamProviderUpdateOne {
	_u.mutation.SetSyncEnabled(v)
	return _u
}

// SetNillableSyncEnabled sets the "sync_enabled" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableSyncEnabled(v *bool) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetSyncEnabled(*v)
	}
	return _u
}

// AddGroupIDs adds the "groups" edge to the UpstreamGroup entity by IDs.
func (_u *UpstreamProviderUpdateOne) AddGroupIDs(ids ...int64) *UpstreamProviderUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamProviderUpdateOne) AddGroups(v ...*UpstreamGroup) *UpstreamProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *UpstreamProviderUpdateOne) AddAccountIDs(ids ...int64) *UpstreamProviderUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *UpstreamProviderUpdateOne) AddAccounts(v ...*Account) *UpstreamProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_u *UpstreamProviderUpdateOne) Mutation() *UpstreamProviderMutation {
	return _u.mutation
}

// ClearGroups clears all "groups" edges to the UpstreamGroup entity.
func (_u *UpstreamProviderUpdateOne) ClearGroups() *UpstreamProviderUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to UpstreamGroup entities by IDs.
func (_u *UpstreamProviderUpdateOne) RemoveGroupIDs(ids ...int64) *UpstreamProviderUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to UpstreamGroup entities.
func (_u *UpstreamProviderUpdateOne) RemoveGroups(v ...*UpstreamGroup) *UpstreamProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *UpstreamProviderUpdateOne) ClearAccounts() *UpstreamProviderUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *UpstreamProviderUpdateOne) RemoveAccountIDs(ids ...int64) *UpstreamProviderUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *UpstreamProviderUpdateOne) RemoveAccounts(v ...*Account) *UpstreamProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the UpstreamProviderUpdate builder.
func (_u *UpstreamProviderUpdateOne) Where(ps ...predicate.UpstreamProvider) *UpstreamProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamProviderUpdateOne) Select(field string, fields ...string) *UpstreamProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamProvider entity.
func (_u *UpstreamProviderUpdateOne) Save(ctx context.Context) (*UpstreamProvider, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamProviderUpdateOne) SaveX(ctx context.Context) *UpstreamProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamProviderUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if upstreamprovider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamprovider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := upstreamprovider.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamUserID(); ok {
		if err := upstreamprovider.UpstreamUserIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_user_id", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.upstream_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamProviderUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamprovider.Table, upstreamprovider.Columns, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamprovider.FieldID)
		for _, f := range fields {
			if !upstreamprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(upstreamprovider.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(upstreamprovider.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(upstreamprovider.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(upstreamprovider.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotpSecretEncrypted(); ok {
		_spec.SetField(upstreamprovider.FieldTotpSecretEncrypted, field.TypeString, value)
	}
	if _u.mutation.TotpSecretEncryptedCleared() {
		_spec.ClearField(upstreamprovider.FieldTotpSecretEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenEncrypted(); ok {
		_spec.SetField(upstreamprovider.FieldTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.TokenEncryptedCleared() {
		_spec.ClearField(upstreamprovider.FieldTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstreamprovider.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(upstreamprovider.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(upstreamprovider.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(upstreamprovider.FieldBalance, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(upstreamprovider.FieldBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.FrozenBalance(); ok {
		_spec.SetField(upstreamprovider.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBalance(); ok {
		_spec.AddField(upstreamprovider.FieldFrozenBalance, field.TypeFloat64, value)
	}
	if _u.mutation.FrozenBalanceCleared() {
		_spec.ClearField(upstreamprovider.FieldFrozenBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpstreamConcurrency(); ok {
		_spec.SetField(upstreamprovider.FieldUpstreamConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpstreamConcurrency(); ok {
		_spec.AddField(upstreamprovider.FieldUpstreamConcurrency, field.TypeInt, value)
	}
	if _u.mutation.UpstreamConcurrencyCleared() {
		_spec.ClearField(upstreamprovider.FieldUpstreamConcurrency, field.TypeInt)
	}
	if value, ok := _u.mutation.UpstreamUserID(); ok {
		_spec.SetField(upstreamprovider.FieldUpstreamUserID, field.TypeString, value)
	}
	if _u.mutation.UpstreamUserIDCleared() {
		_spec.ClearField(upstreamprovider.FieldUpstreamUserID, field.TypeString)
	}
	if value, ok := _u.mutation.RateCorrection(); ok {
		_spec.SetField(upstreamprovider.FieldRateCorrection, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateCorrection(); ok {
		_spec.AddField(upstreamprovider.FieldRateCorrection, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(upstreamprovider.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(upstreamprovider.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(upstreamprovider.FieldLastSyncError, field.TypeString)
	}
	if value, ok := _u.mutation.SyncEnabled(); ok {
		_spec.SetField(upstreamprovider.FieldSyncEnabled, field.TypeBool, value)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.GroupsTable,
			Columns: []string{upstreamprovider.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.GroupsTable,
			Columns: []string{upstreamprovider.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.GroupsTable,
			Columns: []string{upstreamprovider.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.AccountsTable,
			Columns: []string{upstreamprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.AccountsTable,
			Columns: []string{upstreamprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamprovider.AccountsTable,
			Columns: []string{upstreamprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
