// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamprovider"
)

// UpstreamGroup is the model entity for the UpstreamGroup schema.
type UpstreamGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpstreamProviderID holds the value of the "upstream_provider_id" field.
	UpstreamProviderID int64 `json:"upstream_provider_id,omitempty"`
	// RemoteGroupID holds the value of the "remote_group_id" field.
	RemoteGroupID int64 `json:"remote_group_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// SubscriptionType holds the value of the "subscription_type" field.
	SubscriptionType string `json:"subscription_type,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// EffectiveRateMultiplier holds the value of the "effective_rate_multiplier" field.
	EffectiveRateMultiplier *float64 `json:"effective_rate_multiplier,omitempty"`
	// PeakRateEnabled holds the value of the "peak_rate_enabled" field.
	PeakRateEnabled bool `json:"peak_rate_enabled,omitempty"`
	// PeakRateMultiplier holds the value of the "peak_rate_multiplier" field.
	PeakRateMultiplier *float64 `json:"peak_rate_multiplier,omitempty"`
	// PeakStart holds the value of the "peak_start" field.
	PeakStart string `json:"peak_start,omitempty"`
	// PeakEnd holds the value of the "peak_end" field.
	PeakEnd string `json:"peak_end,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd *float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamGroupQuery when eager-loading is set.
	Edges        UpstreamGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamGroupEdges holds the relations/edges for other nodes in the graph.
type UpstreamGroupEdges struct {
	// Provider holds the value of the provider edge.
	Provider *UpstreamProvider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamGroupEdges) ProviderOrErr() (*UpstreamProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreamprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamgroup.FieldPeakRateEnabled:
			values[i] = new(sql.NullBool)
		case upstreamgroup.FieldRateMultiplier, upstreamgroup.FieldEffectiveRateMultiplier, upstreamgroup.FieldPeakRateMultiplier, upstreamgroup.FieldDailyLimitUsd, upstreamgroup.FieldWeeklyLimitUsd, upstreamgroup.FieldMonthlyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case upstreamgroup.FieldID, upstreamgroup.FieldUpstreamProviderID, upstreamgroup.FieldRemoteGroupID:
			values[i] = new(sql.NullInt64)
		case upstreamgroup.FieldName, upstreamgroup.FieldPlatform, upstreamgroup.FieldSubscriptionType, upstreamgroup.FieldPeakStart, upstreamgroup.FieldPeakEnd:
			values[i] = new(sql.NullString)
		case upstreamgroup.FieldCreatedAt, upstreamgroup.FieldUpdatedAt, upstreamgroup.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamGroup fields.
func (_m *UpstreamGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamgroup.FieldUpstreamProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_provider_id", values[i])
			} else if value.Valid {
				_m.UpstreamProviderID = value.Int64
			}
		case upstreamgroup.FieldRemoteGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remote_group_id", values[i])
			} else if value.Valid {
				_m.RemoteGroupID = value.Int64
			}
		case upstreamgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamgroup.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case upstreamgroup.FieldSubscriptionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_type", values[i])
			} else if value.Valid {
				_m.SubscriptionType = value.String
			}
		case upstreamgroup.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case upstreamgroup.FieldEffectiveRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field effective_rate_multiplier", values[i])
			} else if value.Valid {
				_m.EffectiveRateMultiplier = new(float64)
				*_m.EffectiveRateMultiplier = value.Float64
			}
		case upstreamgroup.FieldPeakRateEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field peak_rate_enabled", values[i])
			} else if value.Valid {
				_m.PeakRateEnabled = value.Bool
			}
		case upstreamgroup.FieldPeakRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_rate_multiplier", values[i])
			} else if value.Valid {
				_m.PeakRateMultiplier = new(float64)
				*_m.PeakRateMultiplier = value.Float64
			}
		case upstreamgroup.FieldPeakStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field peak_start", values[i])
			} else if value.Valid {
				_m.PeakStart = value.String
			}
		case upstreamgroup.FieldPeakEnd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field peak_end", values[i])
			} else if value.Valid {
				_m.PeakEnd = value.String
			}
		case upstreamgroup.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case upstreamgroup.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = new(float64)
				*_m.WeeklyLimitUsd = value.Float64
			}
		case upstreamgroup.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		case upstreamgroup.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamGroup.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the UpstreamGroup entity.
func (_m *UpstreamGroup) QueryProvider() *UpstreamProviderQuery {
	return NewUpstreamGroupClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this UpstreamGroup.
// Note that you need to call UpstreamGroup.Unwrap() before calling this method if this UpstreamGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamGroup) Update() *UpstreamGroupUpdateOne {
	return NewUpstreamGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamGroup) Unwrap() *UpstreamGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamGroup) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("upstream_provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamProviderID))
	builder.WriteString(", ")
	builder.WriteString("remote_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemoteGroupID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("subscription_type=")
	builder.WriteString(_m.SubscriptionType)
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	if v := _m.EffectiveRateMultiplier; v != nil {
		builder.WriteString("effective_rate_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("peak_rate_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakRateEnabled))
	builder.WriteString(", ")
	if v := _m.PeakRateMultiplier; v != nil {
		builder.WriteString("peak_rate_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("peak_start=")
	builder.WriteString(_m.PeakStart)
	builder.WriteString(", ")
	builder.WriteString("peak_end=")
	builder.WriteString(_m.PeakEnd)
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyLimitUsd; v != nil {
		builder.WriteString("weekly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamGroups is a parsable slice of UpstreamGroup.
type UpstreamGroups []*UpstreamGroup
