// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/upstreamprovider"
)

// UpstreamGroupCreate is the builder for creating a UpstreamGroup entity.
type UpstreamGroupCreate struct {
	config
	mutation *UpstreamGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamGroupCreate) SetCreatedAt(v time.Time) *UpstreamGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableCreatedAt(v *time.Time) *UpstreamGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamGroupCreate) SetUpdatedAt(v time.Time) *UpstreamGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpstreamProviderID sets the "upstream_provider_id" field.
func (_c *UpstreamGroupCreate) SetUpstreamProviderID(v int64) *UpstreamGroupCreate {
	_c.mutation.SetUpstreamProviderID(v)
	return _c
}

// SetRemoteGroupID sets the "remote_group_id" field.
func (_c *UpstreamGroupCreate) SetRemoteGroupID(v int64) *UpstreamGroupCreate {
	_c.mutation.SetRemoteGroupID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamGroupCreate) SetName(v string) *UpstreamGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *UpstreamGroupCreate) SetPlatform(v string) *UpstreamGroupCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillablePlatform(v *string) *UpstreamGroupCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetSubscriptionType sets the "subscription_type" field.
func (_c *UpstreamGroupCreate) SetSubscriptionType(v string) *UpstreamGroupCreate {
	_c.mutation.SetSubscriptionType(v)
	return _c
}

// SetNillableSubscriptionType sets the "subscription_type" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableSubscriptionType(v *string) *UpstreamGroupCreate {
	if v != nil {
		_c.SetSubscriptionType(*v)
	}
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *UpstreamGroupCreate) SetRateMultiplier(v float64) *UpstreamGroupCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableRateMultiplier(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetRateMultiplier(*v)
	}
	return _c
}

// SetEffectiveRateMultiplier sets the "effective_rate_multiplier" field.
func (_c *UpstreamGroupCreate) SetEffectiveRateMultiplier(v float64) *UpstreamGroupCreate {
	_c.mutation.SetEffectiveRateMultiplier(v)
	return _c
}

// SetNillableEffectiveRateMultiplier sets the "effective_rate_multiplier" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableEffectiveRateMultiplier(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetEffectiveRateMultiplier(*v)
	}
	return _c
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (_c *UpstreamGroupCreate) SetPeakRateEnabled(v bool) *UpstreamGroupCreate {
	_c.mutation.SetPeakRateEnabled(v)
	return _c
}

// SetNillablePeakRateEnabled sets the "peak_rate_enabled" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillablePeakRateEnabled(v *bool) *UpstreamGroupCreate {
	if v != nil {
		_c.SetPeakRateEnabled(*v)
	}
	return _c
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (_c *UpstreamGroupCreate) SetPeakRateMultiplier(v float64) *UpstreamGroupCreate {
	_c.mutation.SetPeakRateMultiplier(v)
	return _c
}

// SetNillablePeakRateMultiplier sets the "peak_rate_multiplier" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillablePeakRateMultiplier(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetPeakRateMultiplier(*v)
	}
	return _c
}

// SetPeakStart sets the "peak_start" field.
func (_c *UpstreamGroupCreate) SetPeakStart(v string) *UpstreamGroupCreate {
	_c.mutation.SetPeakStart(v)
	return _c
}

// SetNillablePeakStart sets the "peak_start" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillablePeakStart(v *string) *UpstreamGroupCreate {
	if v != nil {
		_c.SetPeakStart(*v)
	}
	return _c
}

// SetPeakEnd sets the "peak_end" field.
func (_c *UpstreamGroupCreate) SetPeakEnd(v string) *UpstreamGroupCreate {
	_c.mutation.SetPeakEnd(v)
	return _c
}

// SetNillablePeakEnd sets the "peak_end" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillablePeakEnd(v *string) *UpstreamGroupCreate {
	if v != nil {
		_c.SetPeakEnd(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *UpstreamGroupCreate) SetDailyLimitUsd(v float64) *UpstreamGroupCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableDailyLimitUsd(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *UpstreamGroupCreate) SetWeeklyLimitUsd(v float64) *UpstreamGroupCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableWeeklyLimitUsd(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *UpstreamGroupCreate) SetMonthlyLimitUsd(v float64) *UpstreamGroupCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *UpstreamGroupCreate) SetNillableMonthlyLimitUsd(v *float64) *UpstreamGroupCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *UpstreamGroupCreate) SetSyncedAt(v time.Time) *UpstreamGroupCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetProviderID sets the "provider" edge to the UpstreamProvider entity by ID.
func (_c *UpstreamGroupCreate) SetProviderID(id int64) *UpstreamGroupCreate {
	_c.mutation.SetProviderID(id)
	return _c
}

// SetProvider sets the "provider" edge to the UpstreamProvider entity.
func (_c *UpstreamGroupCreate) SetProvider(v *UpstreamProvider) *UpstreamGroupCreate {
	return _c.SetProviderID(v.ID)
}

// Mutation returns the UpstreamGroupMutation object of the builder.
func (_c *UpstreamGroupCreate) Mutation() *UpstreamGroupMutation {
	return _c.mutation
}

// Save creates the UpstreamGroup in the database.
func (_c *UpstreamGroupCreate) Save(ctx context.Context) (*UpstreamGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamGroupCreate) SaveX(ctx context.Context) *UpstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := upstreamgroup.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.SubscriptionType(); !ok {
		v := upstreamgroup.DefaultSubscriptionType
		_c.mutation.SetSubscriptionType(v)
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		v := upstreamgroup.DefaultRateMultiplier
		_c.mutation.SetRateMultiplier(v)
	}
	if _, ok := _c.mutation.PeakRateEnabled(); !ok {
		v := upstreamgroup.DefaultPeakRateEnabled
		_c.mutation.SetPeakRateEnabled(v)
	}
	if _, ok := _c.mutation.PeakStart(); !ok {
		v := upstreamgroup.DefaultPeakStart
		_c.mutation.SetPeakStart(v)
	}
	if _, ok := _c.mutation.PeakEnd(); !ok {
		v := upstreamgroup.DefaultPeakEnd
		_c.mutation.SetPeakEnd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.UpstreamProviderID(); !ok {
		return &ValidationError{Name: "upstream_provider_id", err: errors.New(`ent: missing required field "UpstreamGroup.upstream_provider_id"`)}
	}
	if _, ok := _c.mutation.RemoteGroupID(); !ok {
		return &ValidationError{Name: "remote_group_id", err: errors.New(`ent: missing required field "UpstreamGroup.remote_group_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "UpstreamGroup.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := upstreamgroup.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionType(); !ok {
		return &ValidationError{Name: "subscription_type", err: errors.New(`ent: missing required field "UpstreamGroup.subscription_type"`)}
	}
	if v, ok := _c.mutation.SubscriptionType(); ok {
		if err := upstreamgroup.SubscriptionTypeValidator(v); err != nil {
			return &ValidationError{Name: "subscription_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.subscription_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "UpstreamGroup.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.PeakRateEnabled(); !ok {
		return &ValidationError{Name: "peak_rate_enabled", err: errors.New(`ent: missing required field "UpstreamGroup.peak_rate_enabled"`)}
	}
	if _, ok := _c.mutation.PeakStart(); !ok {
		return &ValidationError{Name: "peak_start", err: errors.New(`ent: missing required field "UpstreamGroup.peak_start"`)}
	}
	if v, ok := _c.mutation.PeakStart(); ok {
		if err := upstreamgroup.PeakStartValidator(v); err != nil {
			return &ValidationError{Name: "peak_start", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.peak_start": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeakEnd(); !ok {
		return &ValidationError{Name: "peak_end", err: errors.New(`ent: missing required field "UpstreamGroup.peak_end"`)}
	}
	if v, ok := _c.mutation.PeakEnd(); ok {
		if err := upstreamgroup.PeakEndValidator(v); err != nil {
			return &ValidationError{Name: "peak_end", err: fmt.Errorf(`ent: validator failed for field "UpstreamGroup.peak_end": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "UpstreamGroup.synced_at"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "UpstreamGroup.provider"`)}
	}
	return nil
}

func (_c *UpstreamGroupCreate) sqlSave(ctx context.Context) (*UpstreamGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamGroupCreate) createSpec() (*UpstreamGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamgroup.Table, sqlgraph.NewFieldSpec(upstreamgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RemoteGroupID(); ok {
		_spec.SetField(upstreamgroup.FieldRemoteGroupID, field.TypeInt64, value)
		_node.RemoteGroupID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(upstreamgroup.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.SubscriptionType(); ok {
		_spec.SetField(upstreamgroup.FieldSubscriptionType, field.TypeString, value)
		_node.SubscriptionType = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(upstreamgroup.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.EffectiveRateMultiplier(); ok {
		_spec.SetField(upstreamgroup.FieldEffectiveRateMultiplier, field.TypeFloat64, value)
		_node.EffectiveRateMultiplier = &value
	}
	if value, ok := _c.mutation.PeakRateEnabled(); ok {
		_spec.SetField(upstreamgroup.FieldPeakRateEnabled, field.TypeBool, value)
		_node.PeakRateEnabled = value
	}
	if value, ok := _c.mutation.PeakRateMultiplier(); ok {
		_spec.SetField(upstreamgroup.FieldPeakRateMultiplier, field.TypeFloat64, value)
		_node.PeakRateMultiplier = &value
	}
	if value, ok := _c.mutation.PeakStart(); ok {
		_spec.SetField(upstreamgroup.FieldPeakStart, field.TypeString, value)
		_node.PeakStart = value
	}
	if value, ok := _c.mutation.PeakEnd(); ok {
		_spec.SetField(upstreamgroup.FieldPeakEnd, field.TypeString, value)
		_node.PeakEnd = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(upstreamgroup.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = &value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(upstreamgroup.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = &value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(upstreamgroup.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = &value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(upstreamgroup.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamgroup.ProviderTable,
			Columns: []string{upstreamgroup.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpstreamProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamGroupCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamGroupUpsertOne {
	_c.conflict = opts
	return &UpstreamGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamGroupCreate) OnConflictColumns(columns ...string) *UpstreamGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamGroupUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamGroupUpsertOne is the builder for "upsert"-ing
	//  one UpstreamGroup node.
	UpstreamGroupUpsertOne struct {
		create *UpstreamGroupCreate
	}

	// UpstreamGroupUpsert is the "OnConflict" setter.
	UpstreamGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamGroupUpsert) SetUpdatedAt(v time.Time) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateUpdatedAt() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldUpdatedAt)
	return u
}

// SetUpstreamProviderID sets the "upstream_provider_id" field.
func (u *UpstreamGroupUpsert) SetUpstreamProviderID(v int64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldUpstreamProviderID, v)
	return u
}

// UpdateUpstreamProviderID sets the "upstream_provider_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateUpstreamProviderID() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldUpstreamProviderID)
	return u
}

// SetRemoteGroupID sets the "remote_group_id" field.
func (u *UpstreamGroupUpsert) SetRemoteGroupID(v int64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldRemoteGroupID, v)
	return u
}

// UpdateRemoteGroupID sets the "remote_group_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateRemoteGroupID() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldRemoteGroupID)
	return u
}

// AddRemoteGroupID adds v to the "remote_group_id" field.
func (u *UpstreamGroupUpsert) AddRemoteGroupID(v int64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldRemoteGroupID, v)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamGroupUpsert) SetName(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateName() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *UpstreamGroupUpsert) SetPlatform(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdatePlatform() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldPlatform)
	return u
}

// SetSubscriptionType sets the "subscription_type" field.
func (u *UpstreamGroupUpsert) SetSubscriptionType(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldSubscriptionType, v)
	return u
}

// UpdateSubscriptionType sets the "subscription_type" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateSubscriptionType() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldSubscriptionType)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *UpstreamGroupUpsert) SetRateMultiplier(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateRateMultiplier() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *UpstreamGroupUpsert) AddRateMultiplier(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldRateMultiplier, v)
	return u
}

// SetEffectiveRateMultiplier sets the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsert) SetEffectiveRateMultiplier(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldEffectiveRateMultiplier, v)
	return u
}

// UpdateEffectiveRateMultiplier sets the "effective_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateEffectiveRateMultiplier() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldEffectiveRateMultiplier)
	return u
}

// AddEffectiveRateMultiplier adds v to the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsert) AddEffectiveRateMultiplier(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldEffectiveRateMultiplier, v)
	return u
}

// ClearEffectiveRateMultiplier clears the value of the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsert) ClearEffectiveRateMultiplier() *UpstreamGroupUpsert {
	u.SetNull(upstreamgroup.FieldEffectiveRateMultiplier)
	return u
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (u *UpstreamGroupUpsert) SetPeakRateEnabled(v bool) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldPeakRateEnabled, v)
	return u
}

// UpdatePeakRateEnabled sets the "peak_rate_enabled" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdatePeakRateEnabled() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldPeakRateEnabled)
	return u
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsert) SetPeakRateMultiplier(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldPeakRateMultiplier, v)
	return u
}

// UpdatePeakRateMultiplier sets the "peak_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdatePeakRateMultiplier() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldPeakRateMultiplier)
	return u
}

// AddPeakRateMultiplier adds v to the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsert) AddPeakRateMultiplier(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldPeakRateMultiplier, v)
	return u
}

// ClearPeakRateMultiplier clears the value of the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsert) ClearPeakRateMultiplier() *UpstreamGroupUpsert {
	u.SetNull(upstreamgroup.FieldPeakRateMultiplier)
	return u
}

// SetPeakStart sets the "peak_start" field.
func (u *UpstreamGroupUpsert) SetPeakStart(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldPeakStart, v)
	return u
}

// UpdatePeakStart sets the "peak_start" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdatePeakStart() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldPeakStart)
	return u
}

// SetPeakEnd sets the "peak_end" field.
func (u *UpstreamGroupUpsert) SetPeakEnd(v string) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldPeakEnd, v)
	return u
}

// UpdatePeakEnd sets the "peak_end" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdatePeakEnd() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldPeakEnd)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UpstreamGroupUpsert) SetDailyLimitUsd(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateDailyLimitUsd() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UpstreamGroupUpsert) AddDailyLimitUsd(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldDailyLimitUsd, v)
	return u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *UpstreamGroupUpsert) ClearDailyLimitUsd() *UpstreamGroupUpsert {
	u.SetNull(upstreamgroup.FieldDailyLimitUsd)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsert) SetWeeklyLimitUsd(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateWeeklyLimitUsd() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsert) AddWeeklyLimitUsd(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldWeeklyLimitUsd, v)
	return u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsert) ClearWeeklyLimitUsd() *UpstreamGroupUpsert {
	u.SetNull(upstreamgroup.FieldWeeklyLimitUsd)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsert) SetMonthlyLimitUsd(v float64) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateMonthlyLimitUsd() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsert) AddMonthlyLimitUsd(v float64) *UpstreamGroupUpsert {
	u.Add(upstreamgroup.FieldMonthlyLimitUsd, v)
	return u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsert) ClearMonthlyLimitUsd() *UpstreamGroupUpsert {
	u.SetNull(upstreamgroup.FieldMonthlyLimitUsd)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamGroupUpsert) SetSyncedAt(v time.Time) *UpstreamGroupUpsert {
	u.Set(upstreamgroup.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsert) UpdateSyncedAt() *UpstreamGroupUpsert {
	u.SetExcluded(upstreamgroup.FieldSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamGroupUpsertOne) UpdateNewValues() *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamGroupUpsertOne) Ignore() *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamGroupUpsertOne) DoNothing() *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamGroupCreate.OnConflict
// documentation for more info.
func (u *UpstreamGroupUpsertOne) Update(set func(*UpstreamGroupUpsert)) *UpstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamGroupUpsertOne) SetUpdatedAt(v time.Time) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateUpdatedAt() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUpstreamProviderID sets the "upstream_provider_id" field.
func (u *UpstreamGroupUpsertOne) SetUpstreamProviderID(v int64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetUpstreamProviderID(v)
	})
}

// UpdateUpstreamProviderID sets the "upstream_provider_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateUpstreamProviderID() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateUpstreamProviderID()
	})
}

// SetRemoteGroupID sets the "remote_group_id" field.
func (u *UpstreamGroupUpsertOne) SetRemoteGroupID(v int64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetRemoteGroupID(v)
	})
}

// AddRemoteGroupID adds v to the "remote_group_id" field.
func (u *UpstreamGroupUpsertOne) AddRemoteGroupID(v int64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddRemoteGroupID(v)
	})
}

// UpdateRemoteGroupID sets the "remote_group_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateRemoteGroupID() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateRemoteGroupID()
	})
}

// SetName sets the "name" field.
func (u *UpstreamGroupUpsertOne) SetName(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateName() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamGroupUpsertOne) SetPlatform(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdatePlatform() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePlatform()
	})
}

// SetSubscriptionType sets the "subscription_type" field.
func (u *UpstreamGroupUpsertOne) SetSubscriptionType(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetSubscriptionType(v)
	})
}

// UpdateSubscriptionType sets the "subscription_type" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateSubscriptionType() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateSubscriptionType()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) SetRateMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) AddRateMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateRateMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetEffectiveRateMultiplier sets the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) SetEffectiveRateMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetEffectiveRateMultiplier(v)
	})
}

// AddEffectiveRateMultiplier adds v to the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) AddEffectiveRateMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddEffectiveRateMultiplier(v)
	})
}

// UpdateEffectiveRateMultiplier sets the "effective_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateEffectiveRateMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateEffectiveRateMultiplier()
	})
}

// ClearEffectiveRateMultiplier clears the value of the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) ClearEffectiveRateMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearEffectiveRateMultiplier()
	})
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (u *UpstreamGroupUpsertOne) SetPeakRateEnabled(v bool) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakRateEnabled(v)
	})
}

// UpdatePeakRateEnabled sets the "peak_rate_enabled" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdatePeakRateEnabled() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakRateEnabled()
	})
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) SetPeakRateMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakRateMultiplier(v)
	})
}

// AddPeakRateMultiplier adds v to the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) AddPeakRateMultiplier(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddPeakRateMultiplier(v)
	})
}

// UpdatePeakRateMultiplier sets the "peak_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdatePeakRateMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakRateMultiplier()
	})
}

// ClearPeakRateMultiplier clears the value of the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsertOne) ClearPeakRateMultiplier() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearPeakRateMultiplier()
	})
}

// SetPeakStart sets the "peak_start" field.
func (u *UpstreamGroupUpsertOne) SetPeakStart(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakStart(v)
	})
}

// UpdatePeakStart sets the "peak_start" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdatePeakStart() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakStart()
	})
}

// SetPeakEnd sets the "peak_end" field.
func (u *UpstreamGroupUpsertOne) SetPeakEnd(v string) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakEnd(v)
	})
}

// UpdatePeakEnd sets the "peak_end" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdatePeakEnd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakEnd()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UpstreamGroupUpsertOne) SetDailyLimitUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UpstreamGroupUpsertOne) AddDailyLimitUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateDailyLimitUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *UpstreamGroupUpsertOne) ClearDailyLimitUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsertOne) SetWeeklyLimitUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsertOne) AddWeeklyLimitUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateWeeklyLimitUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsertOne) ClearWeeklyLimitUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsertOne) SetMonthlyLimitUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsertOne) AddMonthlyLimitUsd(v float64) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateMonthlyLimitUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsertOne) ClearMonthlyLimitUsd() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamGroupUpsertOne) SetSyncedAt(v time.Time) *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertOne) UpdateSyncedAt() *UpstreamGroupUpsertOne {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamGroupCreateBulk is the builder for creating many UpstreamGroup entities in bulk.
type UpstreamGroupCreateBulk struct {
	config
	err      error
	builders []*UpstreamGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamGroup entities in the database.
func (_c *UpstreamGroupCreateBulk) Save(ctx context.Context) ([]*UpstreamGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamGroupCreateBulk) SaveX(ctx context.Context) []*UpstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamGroupUpsertBulk {
	_c.conflict = opts
	return &UpstreamGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamGroupCreateBulk) OnConflictColumns(columns ...string) *UpstreamGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamGroupUpsertBulk{
		create: _c,
	}
}

// UpstreamGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamGroup nodes.
type UpstreamGroupUpsertBulk struct {
	create *UpstreamGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamGroupUpsertBulk) UpdateNewValues() *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamGroupUpsertBulk) Ignore() *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamGroupUpsertBulk) DoNothing() *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamGroupCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamGroupUpsertBulk) Update(set func(*UpstreamGroupUpsert)) *UpstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamGroupUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateUpdatedAt() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUpstreamProviderID sets the "upstream_provider_id" field.
func (u *UpstreamGroupUpsertBulk) SetUpstreamProviderID(v int64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetUpstreamProviderID(v)
	})
}

// UpdateUpstreamProviderID sets the "upstream_provider_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateUpstreamProviderID() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateUpstreamProviderID()
	})
}

// SetRemoteGroupID sets the "remote_group_id" field.
func (u *UpstreamGroupUpsertBulk) SetRemoteGroupID(v int64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetRemoteGroupID(v)
	})
}

// AddRemoteGroupID adds v to the "remote_group_id" field.
func (u *UpstreamGroupUpsertBulk) AddRemoteGroupID(v int64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddRemoteGroupID(v)
	})
}

// UpdateRemoteGroupID sets the "remote_group_id" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateRemoteGroupID() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateRemoteGroupID()
	})
}

// SetName sets the "name" field.
func (u *UpstreamGroupUpsertBulk) SetName(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateName() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *UpstreamGroupUpsertBulk) SetPlatform(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdatePlatform() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePlatform()
	})
}

// SetSubscriptionType sets the "subscription_type" field.
func (u *UpstreamGroupUpsertBulk) SetSubscriptionType(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetSubscriptionType(v)
	})
}

// UpdateSubscriptionType sets the "subscription_type" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateSubscriptionType() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateSubscriptionType()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) SetRateMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) AddRateMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateRateMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetEffectiveRateMultiplier sets the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) SetEffectiveRateMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetEffectiveRateMultiplier(v)
	})
}

// AddEffectiveRateMultiplier adds v to the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) AddEffectiveRateMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddEffectiveRateMultiplier(v)
	})
}

// UpdateEffectiveRateMultiplier sets the "effective_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateEffectiveRateMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateEffectiveRateMultiplier()
	})
}

// ClearEffectiveRateMultiplier clears the value of the "effective_rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) ClearEffectiveRateMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearEffectiveRateMultiplier()
	})
}

// SetPeakRateEnabled sets the "peak_rate_enabled" field.
func (u *UpstreamGroupUpsertBulk) SetPeakRateEnabled(v bool) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakRateEnabled(v)
	})
}

// UpdatePeakRateEnabled sets the "peak_rate_enabled" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdatePeakRateEnabled() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakRateEnabled()
	})
}

// SetPeakRateMultiplier sets the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) SetPeakRateMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakRateMultiplier(v)
	})
}

// AddPeakRateMultiplier adds v to the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) AddPeakRateMultiplier(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddPeakRateMultiplier(v)
	})
}

// UpdatePeakRateMultiplier sets the "peak_rate_multiplier" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdatePeakRateMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakRateMultiplier()
	})
}

// ClearPeakRateMultiplier clears the value of the "peak_rate_multiplier" field.
func (u *UpstreamGroupUpsertBulk) ClearPeakRateMultiplier() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearPeakRateMultiplier()
	})
}

// SetPeakStart sets the "peak_start" field.
func (u *UpstreamGroupUpsertBulk) SetPeakStart(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakStart(v)
	})
}

// UpdatePeakStart sets the "peak_start" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdatePeakStart() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakStart()
	})
}

// SetPeakEnd sets the "peak_end" field.
func (u *UpstreamGroupUpsertBulk) SetPeakEnd(v string) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetPeakEnd(v)
	})
}

// UpdatePeakEnd sets the "peak_end" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdatePeakEnd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdatePeakEnd()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) SetDailyLimitUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) AddDailyLimitUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateDailyLimitUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) ClearDailyLimitUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) SetWeeklyLimitUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) AddWeeklyLimitUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateWeeklyLimitUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) ClearWeeklyLimitUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) SetMonthlyLimitUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) AddMonthlyLimitUsd(v float64) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateMonthlyLimitUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *UpstreamGroupUpsertBulk) ClearMonthlyLimitUsd() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *UpstreamGroupUpsertBulk) SetSyncedAt(v time.Time) *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *UpstreamGroupUpsertBulk) UpdateSyncedAt() *UpstreamGroupUpsertBulk {
	return u.Update(func(s *UpstreamGroupUpsert) {
		s.UpdateSyncedAt()
	})
}

// Exec executes the query.
func (u *UpstreamGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
