// Code generated by ent, DO NOT EDIT.

package ticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorRole applies equality check predicate on the "author_role" field. It's identical to AuthorRoleEQ.
func AuthorRole(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...int64) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorRoleEQ applies the EQ predicate on the "author_role" field.
func AuthorRoleEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// AuthorRoleNEQ applies the NEQ predicate on the "author_role" field.
func AuthorRoleNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldAuthorRole, v))
}

// AuthorRoleIn applies the In predicate on the "author_role" field.
func AuthorRoleIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldAuthorRole, vs...))
}

// AuthorRoleNotIn applies the NotIn predicate on the "author_role" field.
func AuthorRoleNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldAuthorRole, vs...))
}

// AuthorRoleGT applies the GT predicate on the "author_role" field.
func AuthorRoleGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldAuthorRole, v))
}

// AuthorRoleGTE applies the GTE predicate on the "author_role" field.
func AuthorRoleGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldAuthorRole, v))
}

// AuthorRoleLT applies the LT predicate on the "author_role" field.
func AuthorRoleLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldAuthorRole, v))
}

// AuthorRoleLTE applies the LTE predicate on the "author_role" field.
func AuthorRoleLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldAuthorRole, v))
}

// AuthorRoleContains applies the Contains predicate on the "author_role" field.
func AuthorRoleContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldAuthorRole, v))
}

// AuthorRoleHasPrefix applies the HasPrefix predicate on the "author_role" field.
func AuthorRoleHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldAuthorRole, v))
}

// AuthorRoleHasSuffix applies the HasSuffix predicate on the "author_role" field.
func AuthorRoleHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldAuthorRole, v))
}

// AuthorRoleEqualFold applies the EqualFold predicate on the "author_role" field.
func AuthorRoleEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldAuthorRole, v))
}

// AuthorRoleContainsFold applies the ContainsFold predicate on the "author_role" field.
func AuthorRoleContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldAuthorRole, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TicketMessage {
	return predicate.TicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.Ticket) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.TicketMessage {
	return predicate.TicketMessage(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TicketMessage) predicate.TicketMessage {
	return predicate.TicketMessage(sql.NotPredicates(p))
}
