// Code generated by ent, DO NOT EDIT.

package upstreamprovider

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamprovider type in the database.
	Label = "upstream_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordEncrypted holds the string denoting the password_encrypted field in the database.
	FieldPasswordEncrypted = "password_encrypted"
	// FieldTotpSecretEncrypted holds the string denoting the totp_secret_encrypted field in the database.
	FieldTotpSecretEncrypted = "totp_secret_encrypted"
	// FieldTokenEncrypted holds the string denoting the token_encrypted field in the database.
	FieldTokenEncrypted = "token_encrypted"
	// FieldRefreshTokenEncrypted holds the string denoting the refresh_token_encrypted field in the database.
	FieldRefreshTokenEncrypted = "refresh_token_encrypted"
	// FieldTokenExpiresAt holds the string denoting the token_expires_at field in the database.
	FieldTokenExpiresAt = "token_expires_at"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldFrozenBalance holds the string denoting the frozen_balance field in the database.
	FieldFrozenBalance = "frozen_balance"
	// FieldUpstreamConcurrency holds the string denoting the upstream_concurrency field in the database.
	FieldUpstreamConcurrency = "upstream_concurrency"
	// FieldUpstreamUserID holds the string denoting the upstream_user_id field in the database.
	FieldUpstreamUserID = "upstream_user_id"
	// FieldRateCorrection holds the string denoting the rate_correction field in the database.
	FieldRateCorrection = "rate_correction"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// FieldLastSyncError holds the string denoting the last_sync_error field in the database.
	FieldLastSyncError = "last_sync_error"
	// FieldSyncEnabled holds the string denoting the sync_enabled field in the database.
	FieldSyncEnabled = "sync_enabled"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// Table holds the table name of the upstreamprovider in the database.
	Table = "upstream_providers"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "upstream_groups"
	// GroupsInverseTable is the table name for the UpstreamGroup entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamgroup" package.
	GroupsInverseTable = "upstream_groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "upstream_provider_id"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "upstream_provider_id"
)

// Columns holds all SQL columns for upstreamprovider fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldBaseURL,
	FieldNotes,
	FieldUsername,
	FieldPasswordEncrypted,
	FieldTotpSecretEncrypted,
	FieldTokenEncrypted,
	FieldRefreshTokenEncrypted,
	FieldTokenExpiresAt,
	FieldBalance,
	FieldFrozenBalance,
	FieldUpstreamConcurrency,
	FieldUpstreamUserID,
	FieldRateCorrection,
	FieldStatus,
	FieldLastSyncAt,
	FieldLastSyncError,
	FieldSyncEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// UpstreamUserIDValidator is a validator for the "upstream_user_id" field. It is called by the builders before save.
	UpstreamUserIDValidator func(string) error
	// DefaultRateCorrection holds the default value on creation for the "rate_correction" field.
	DefaultRateCorrection float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSyncEnabled holds the default value on creation for the "sync_enabled" field.
	DefaultSyncEnabled bool
)

// OrderOption defines the ordering options for the UpstreamProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordEncrypted orders the results by the password_encrypted field.
func ByPasswordEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordEncrypted, opts...).ToFunc()
}

// ByTotpSecretEncrypted orders the results by the totp_secret_encrypted field.
func ByTotpSecretEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotpSecretEncrypted, opts...).ToFunc()
}

// ByTokenEncrypted orders the results by the token_encrypted field.
func ByTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenEncrypted, opts...).ToFunc()
}

// ByRefreshTokenEncrypted orders the results by the refresh_token_encrypted field.
func ByRefreshTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenEncrypted, opts...).ToFunc()
}

// ByTokenExpiresAt orders the results by the token_expires_at field.
func ByTokenExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenExpiresAt, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByFrozenBalance orders the results by the frozen_balance field.
func ByFrozenBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenBalance, opts...).ToFunc()
}

// ByUpstreamConcurrency orders the results by the upstream_concurrency field.
func ByUpstreamConcurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamConcurrency, opts...).ToFunc()
}

// ByUpstreamUserID orders the results by the upstream_user_id field.
func ByUpstreamUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamUserID, opts...).ToFunc()
}

// ByRateCorrection orders the results by the rate_correction field.
func ByRateCorrection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateCorrection, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByLastSyncError orders the results by the last_sync_error field.
func ByLastSyncError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncError, opts...).ToFunc()
}

// BySyncEnabled orders the results by the sync_enabled field.
func BySyncEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncEnabled, opts...).ToFunc()
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
