// Code generated by ent, DO NOT EDIT.

package upstreamprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBaseURL, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldNotes, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUsername, v))
}

// PasswordEncrypted applies equality check predicate on the "password_encrypted" field. It's identical to PasswordEncryptedEQ.
func PasswordEncrypted(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// TotpSecretEncrypted applies equality check predicate on the "totp_secret_encrypted" field. It's identical to TotpSecretEncryptedEQ.
func TotpSecretEncrypted(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTotpSecretEncrypted, v))
}

// TokenEncrypted applies equality check predicate on the "token_encrypted" field. It's identical to TokenEncryptedEQ.
func TokenEncrypted(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTokenEncrypted, v))
}

// TokenExpiresAt applies equality check predicate on the "token_expires_at" field. It's identical to TokenExpiresAtEQ.
func TokenExpiresAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBalance, v))
}

// FrozenBalance applies equality check predicate on the "frozen_balance" field. It's identical to FrozenBalanceEQ.
func FrozenBalance(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldFrozenBalance, v))
}

// UpstreamConcurrency applies equality check predicate on the "upstream_concurrency" field. It's identical to UpstreamConcurrencyEQ.
func UpstreamConcurrency(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpstreamConcurrency, v))
}

// UpstreamUserID applies equality check predicate on the "upstream_user_id" field. It's identical to UpstreamUserIDEQ.
func UpstreamUserID(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpstreamUserID, v))
}

// RateCorrection applies equality check predicate on the "rate_correction" field. It's identical to RateCorrectionEQ.
func RateCorrection(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRateCorrection, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldStatus, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncError applies equality check predicate on the "last_sync_error" field. It's identical to LastSyncErrorEQ.
func LastSyncError(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastSyncError, v))
}

// SyncEnabled applies equality check predicate on the "sync_enabled" field. It's identical to SyncEnabledEQ.
func SyncEnabled(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldSyncEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldBaseURL, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldNotes, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEncryptedEQ applies the EQ predicate on the "password_encrypted" field.
func PasswordEncryptedEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedNEQ applies the NEQ predicate on the "password_encrypted" field.
func PasswordEncryptedNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedIn applies the In predicate on the "password_encrypted" field.
func PasswordEncryptedIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedNotIn applies the NotIn predicate on the "password_encrypted" field.
func PasswordEncryptedNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedGT applies the GT predicate on the "password_encrypted" field.
func PasswordEncryptedGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedGTE applies the GTE predicate on the "password_encrypted" field.
func PasswordEncryptedGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLT applies the LT predicate on the "password_encrypted" field.
func PasswordEncryptedLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLTE applies the LTE predicate on the "password_encrypted" field.
func PasswordEncryptedLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContains applies the Contains predicate on the "password_encrypted" field.
func PasswordEncryptedContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasPrefix applies the HasPrefix predicate on the "password_encrypted" field.
func PasswordEncryptedHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasSuffix applies the HasSuffix predicate on the "password_encrypted" field.
func PasswordEncryptedHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedEqualFold applies the EqualFold predicate on the "password_encrypted" field.
func PasswordEncryptedEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContainsFold applies the ContainsFold predicate on the "password_encrypted" field.
func PasswordEncryptedContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldPasswordEncrypted, v))
}

// TotpSecretEncryptedEQ applies the EQ predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedNEQ applies the NEQ predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedIn applies the In predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldTotpSecretEncrypted, vs...))
}

// TotpSecretEncryptedNotIn applies the NotIn predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldTotpSecretEncrypted, vs...))
}

// TotpSecretEncryptedGT applies the GT predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedGTE applies the GTE predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedLT applies the LT predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedLTE applies the LTE predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedContains applies the Contains predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedHasPrefix applies the HasPrefix predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedHasSuffix applies the HasSuffix predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedIsNil applies the IsNil predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldTotpSecretEncrypted))
}

// TotpSecretEncryptedNotNil applies the NotNil predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldTotpSecretEncrypted))
}

// TotpSecretEncryptedEqualFold applies the EqualFold predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldTotpSecretEncrypted, v))
}

// TotpSecretEncryptedContainsFold applies the ContainsFold predicate on the "totp_secret_encrypted" field.
func TotpSecretEncryptedContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldTotpSecretEncrypted, v))
}

// TokenEncryptedEQ applies the EQ predicate on the "token_encrypted" field.
func TokenEncryptedEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTokenEncrypted, v))
}

// TokenEncryptedNEQ applies the NEQ predicate on the "token_encrypted" field.
func TokenEncryptedNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldTokenEncrypted, v))
}

// TokenEncryptedIn applies the In predicate on the "token_encrypted" field.
func TokenEncryptedIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldTokenEncrypted, vs...))
}

// TokenEncryptedNotIn applies the NotIn predicate on the "token_encrypted" field.
func TokenEncryptedNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldTokenEncrypted, vs...))
}

// TokenEncryptedGT applies the GT predicate on the "token_encrypted" field.
func TokenEncryptedGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldTokenEncrypted, v))
}

// TokenEncryptedGTE applies the GTE predicate on the "token_encrypted" field.
func TokenEncryptedGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldTokenEncrypted, v))
}

// TokenEncryptedLT applies the LT predicate on the "token_encrypted" field.
func TokenEncryptedLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldTokenEncrypted, v))
}

// TokenEncryptedLTE applies the LTE predicate on the "token_encrypted" field.
func TokenEncryptedLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldTokenEncrypted, v))
}

// TokenEncryptedContains applies the Contains predicate on the "token_encrypted" field.
func TokenEncryptedContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldTokenEncrypted, v))
}

// TokenEncryptedHasPrefix applies the HasPrefix predicate on the "token_encrypted" field.
func TokenEncryptedHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldTokenEncrypted, v))
}

// TokenEncryptedHasSuffix applies the HasSuffix predicate on the "token_encrypted" field.
func TokenEncryptedHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldTokenEncrypted, v))
}

// TokenEncryptedIsNil applies the IsNil predicate on the "token_encrypted" field.
func TokenEncryptedIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldTokenEncrypted))
}

// TokenEncryptedNotNil applies the NotNil predicate on the "token_encrypted" field.
func TokenEncryptedNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldTokenEncrypted))
}

// TokenEncryptedEqualFold applies the EqualFold predicate on the "token_encrypted" field.
func TokenEncryptedEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldTokenEncrypted, v))
}

// TokenEncryptedContainsFold applies the ContainsFold predicate on the "token_encrypted" field.
func TokenEncryptedContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldTokenEncrypted, v))
}

// TokenExpiresAtEQ applies the EQ predicate on the "token_expires_at" field.
func TokenExpiresAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtNEQ applies the NEQ predicate on the "token_expires_at" field.
func TokenExpiresAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIn applies the In predicate on the "token_expires_at" field.
func TokenExpiresAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtNotIn applies the NotIn predicate on the "token_expires_at" field.
func TokenExpiresAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtGT applies the GT predicate on the "token_expires_at" field.
func TokenExpiresAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtGTE applies the GTE predicate on the "token_expires_at" field.
func TokenExpiresAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLT applies the LT predicate on the "token_expires_at" field.
func TokenExpiresAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLTE applies the LTE predicate on the "token_expires_at" field.
func TokenExpiresAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIsNil applies the IsNil predicate on the "token_expires_at" field.
func TokenExpiresAtIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldTokenExpiresAt))
}

// TokenExpiresAtNotNil applies the NotNil predicate on the "token_expires_at" field.
func TokenExpiresAtNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldTokenExpiresAt))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldBalance, v))
}

// BalanceIsNil applies the IsNil predicate on the "balance" field.
func BalanceIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldBalance))
}

// BalanceNotNil applies the NotNil predicate on the "balance" field.
func BalanceNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldBalance))
}

// FrozenBalanceEQ applies the EQ predicate on the "frozen_balance" field.
func FrozenBalanceEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldFrozenBalance, v))
}

// FrozenBalanceNEQ applies the NEQ predicate on the "frozen_balance" field.
func FrozenBalanceNEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldFrozenBalance, v))
}

// FrozenBalanceIn applies the In predicate on the "frozen_balance" field.
func FrozenBalanceIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldFrozenBalance, vs...))
}

// FrozenBalanceNotIn applies the NotIn predicate on the "frozen_balance" field.
func FrozenBalanceNotIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldFrozenBalance, vs...))
}

// FrozenBalanceGT applies the GT predicate on the "frozen_balance" field.
func FrozenBalanceGT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldFrozenBalance, v))
}

// FrozenBalanceGTE applies the GTE predicate on the "frozen_balance" field.
func FrozenBalanceGTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldFrozenBalance, v))
}

// FrozenBalanceLT applies the LT predicate on the "frozen_balance" field.
func FrozenBalanceLT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldFrozenBalance, v))
}

// FrozenBalanceLTE applies the LTE predicate on the "frozen_balance" field.
func FrozenBalanceLTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldFrozenBalance, v))
}

// FrozenBalanceIsNil applies the IsNil predicate on the "frozen_balance" field.
func FrozenBalanceIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldFrozenBalance))
}

// FrozenBalanceNotNil applies the NotNil predicate on the "frozen_balance" field.
func FrozenBalanceNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldFrozenBalance))
}

// UpstreamConcurrencyEQ applies the EQ predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyEQ(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpstreamConcurrency, v))
}

// UpstreamConcurrencyNEQ applies the NEQ predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyNEQ(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldUpstreamConcurrency, v))
}

// UpstreamConcurrencyIn applies the In predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyIn(vs ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldUpstreamConcurrency, vs...))
}

// UpstreamConcurrencyNotIn applies the NotIn predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyNotIn(vs ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldUpstreamConcurrency, vs...))
}

// UpstreamConcurrencyGT applies the GT predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyGT(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldUpstreamConcurrency, v))
}

// UpstreamConcurrencyGTE applies the GTE predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyGTE(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldUpstreamConcurrency, v))
}

// UpstreamConcurrencyLT applies the LT predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyLT(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldUpstreamConcurrency, v))
}

// UpstreamConcurrencyLTE applies the LTE predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyLTE(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldUpstreamConcurrency, v))
}

// UpstreamConcurrencyIsNil applies the IsNil predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldUpstreamConcurrency))
}

// UpstreamConcurrencyNotNil applies the NotNil predicate on the "upstream_concurrency" field.
func UpstreamConcurrencyNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldUpstreamConcurrency))
}

// UpstreamUserIDEQ applies the EQ predicate on the "upstream_user_id" field.
func UpstreamUserIDEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpstreamUserID, v))
}

// UpstreamUserIDNEQ applies the NEQ predicate on the "upstream_user_id" field.
func UpstreamUserIDNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldUpstreamUserID, v))
}

// UpstreamUserIDIn applies the In predicate on the "upstream_user_id" field.
func UpstreamUserIDIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldUpstreamUserID, vs...))
}

// UpstreamUserIDNotIn applies the NotIn predicate on the "upstream_user_id" field.
func UpstreamUserIDNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldUpstreamUserID, vs...))
}

// UpstreamUserIDGT applies the GT predicate on the "upstream_user_id" field.
func UpstreamUserIDGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldUpstreamUserID, v))
}

// UpstreamUserIDGTE applies the GTE predicate on the "upstream_user_id" field.
func UpstreamUserIDGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldUpstreamUserID, v))
}

// UpstreamUserIDLT applies the LT predicate on the "upstream_user_id" field.
func UpstreamUserIDLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldUpstreamUserID, v))
}

// UpstreamUserIDLTE applies the LTE predicate on the "upstream_user_id" field.
func UpstreamUserIDLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldUpstreamUserID, v))
}

// UpstreamUserIDContains applies the Contains predicate on the "upstream_user_id" field.
func UpstreamUserIDContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldUpstreamUserID, v))
}

// UpstreamUserIDHasPrefix applies the HasPrefix predicate on the "upstream_user_id" field.
func UpstreamUserIDHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldUpstreamUserID, v))
}

// UpstreamUserIDHasSuffix applies the HasSuffix predicate on the "upstream_user_id" field.
func UpstreamUserIDHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldUpstreamUserID, v))
}

// UpstreamUserIDIsNil applies the IsNil predicate on the "upstream_user_id" field.
func UpstreamUserIDIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldUpstreamUserID))
}

// UpstreamUserIDNotNil applies the NotNil predicate on the "upstream_user_id" field.
func UpstreamUserIDNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldUpstreamUserID))
}

// UpstreamUserIDEqualFold applies the EqualFold predicate on the "upstream_user_id" field.
func UpstreamUserIDEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldUpstreamUserID, v))
}

// UpstreamUserIDContainsFold applies the ContainsFold predicate on the "upstream_user_id" field.
func UpstreamUserIDContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldUpstreamUserID, v))
}

// RateCorrectionEQ applies the EQ predicate on the "rate_correction" field.
func RateCorrectionEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRateCorrection, v))
}

// RateCorrectionNEQ applies the NEQ predicate on the "rate_correction" field.
func RateCorrectionNEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldRateCorrection, v))
}

// RateCorrectionIn applies the In predicate on the "rate_correction" field.
func RateCorrectionIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldRateCorrection, vs...))
}

// RateCorrectionNotIn applies the NotIn predicate on the "rate_correction" field.
func RateCorrectionNotIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldRateCorrection, vs...))
}

// RateCorrectionGT applies the GT predicate on the "rate_correction" field.
func RateCorrectionGT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldRateCorrection, v))
}

// RateCorrectionGTE applies the GTE predicate on the "rate_correction" field.
func RateCorrectionGTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldRateCorrection, v))
}

// RateCorrectionLT applies the LT predicate on the "rate_correction" field.
func RateCorrectionLT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldRateCorrection, v))
}

// RateCorrectionLTE applies the LTE predicate on the "rate_correction" field.
func RateCorrectionLTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldRateCorrection, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldStatus, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldLastSyncAt))
}

// LastSyncErrorEQ applies the EQ predicate on the "last_sync_error" field.
func LastSyncErrorEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastSyncError, v))
}

// LastSyncErrorNEQ applies the NEQ predicate on the "last_sync_error" field.
func LastSyncErrorNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldLastSyncError, v))
}

// LastSyncErrorIn applies the In predicate on the "last_sync_error" field.
func LastSyncErrorIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldLastSyncError, vs...))
}

// LastSyncErrorNotIn applies the NotIn predicate on the "last_sync_error" field.
func LastSyncErrorNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldLastSyncError, vs...))
}

// LastSyncErrorGT applies the GT predicate on the "last_sync_error" field.
func LastSyncErrorGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldLastSyncError, v))
}

// LastSyncErrorGTE applies the GTE predicate on the "last_sync_error" field.
func LastSyncErrorGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldLastSyncError, v))
}

// LastSyncErrorLT applies the LT predicate on the "last_sync_error" field.
func LastSyncErrorLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldLastSyncError, v))
}

// LastSyncErrorLTE applies the LTE predicate on the "last_sync_error" field.
func LastSyncErrorLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldLastSyncError, v))
}

// LastSyncErrorContains applies the Contains predicate on the "last_sync_error" field.
func LastSyncErrorContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldLastSyncError, v))
}

// LastSyncErrorHasPrefix applies the HasPrefix predicate on the "last_sync_error" field.
func LastSyncErrorHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldLastSyncError, v))
}

// LastSyncErrorHasSuffix applies the HasSuffix predicate on the "last_sync_error" field.
func LastSyncErrorHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldLastSyncError, v))
}

// LastSyncErrorIsNil applies the IsNil predicate on the "last_sync_error" field.
func LastSyncErrorIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldLastSyncError))
}

// LastSyncErrorNotNil applies the NotNil predicate on the "last_sync_error" field.
func LastSyncErrorNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldLastSyncError))
}

// LastSyncErrorEqualFold applies the EqualFold predicate on the "last_sync_error" field.
func LastSyncErrorEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldLastSyncError, v))
}

// LastSyncErrorContainsFold applies the ContainsFold predicate on the "last_sync_error" field.
func LastSyncErrorContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldLastSyncError, v))
}

// SyncEnabledEQ applies the EQ predicate on the "sync_enabled" field.
func SyncEnabledEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldSyncEnabled, v))
}

// SyncEnabledNEQ applies the NEQ predicate on the "sync_enabled" field.
func SyncEnabledNEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldSyncEnabled, v))
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.UpstreamGroup) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.NotPredicates(p))
}
