// Code generated by ent, DO NOT EDIT.

package upstreamgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpstreamProviderID applies equality check predicate on the "upstream_provider_id" field. It's identical to UpstreamProviderIDEQ.
func UpstreamProviderID(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldUpstreamProviderID, v))
}

// RemoteGroupID applies equality check predicate on the "remote_group_id" field. It's identical to RemoteGroupIDEQ.
func RemoteGroupID(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldRemoteGroupID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPlatform, v))
}

// SubscriptionType applies equality check predicate on the "subscription_type" field. It's identical to SubscriptionTypeEQ.
func SubscriptionType(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldSubscriptionType, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldRateMultiplier, v))
}

// EffectiveRateMultiplier applies equality check predicate on the "effective_rate_multiplier" field. It's identical to EffectiveRateMultiplierEQ.
func EffectiveRateMultiplier(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldEffectiveRateMultiplier, v))
}

// PeakRateEnabled applies equality check predicate on the "peak_rate_enabled" field. It's identical to PeakRateEnabledEQ.
func PeakRateEnabled(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakRateEnabled, v))
}

// PeakRateMultiplier applies equality check predicate on the "peak_rate_multiplier" field. It's identical to PeakRateMultiplierEQ.
func PeakRateMultiplier(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakRateMultiplier, v))
}

// PeakStart applies equality check predicate on the "peak_start" field. It's identical to PeakStartEQ.
func PeakStart(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakStart, v))
}

// PeakEnd applies equality check predicate on the "peak_end" field. It's identical to PeakEndEQ.
func PeakEnd(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakEnd, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// WeeklyLimitUsd applies equality check predicate on the "weekly_limit_usd" field. It's identical to WeeklyLimitUsdEQ.
func WeeklyLimitUsd(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// MonthlyLimitUsd applies equality check predicate on the "monthly_limit_usd" field. It's identical to MonthlyLimitUsdEQ.
func MonthlyLimitUsd(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpstreamProviderIDEQ applies the EQ predicate on the "upstream_provider_id" field.
func UpstreamProviderIDEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldUpstreamProviderID, v))
}

// UpstreamProviderIDNEQ applies the NEQ predicate on the "upstream_provider_id" field.
func UpstreamProviderIDNEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldUpstreamProviderID, v))
}

// UpstreamProviderIDIn applies the In predicate on the "upstream_provider_id" field.
func UpstreamProviderIDIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldUpstreamProviderID, vs...))
}

// UpstreamProviderIDNotIn applies the NotIn predicate on the "upstream_provider_id" field.
func UpstreamProviderIDNotIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldUpstreamProviderID, vs...))
}

// RemoteGroupIDEQ applies the EQ predicate on the "remote_group_id" field.
func RemoteGroupIDEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldRemoteGroupID, v))
}

// RemoteGroupIDNEQ applies the NEQ predicate on the "remote_group_id" field.
func RemoteGroupIDNEQ(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldRemoteGroupID, v))
}

// RemoteGroupIDIn applies the In predicate on the "remote_group_id" field.
func RemoteGroupIDIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldRemoteGroupID, vs...))
}

// RemoteGroupIDNotIn applies the NotIn predicate on the "remote_group_id" field.
func RemoteGroupIDNotIn(vs ...int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldRemoteGroupID, vs...))
}

// RemoteGroupIDGT applies the GT predicate on the "remote_group_id" field.
func RemoteGroupIDGT(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldRemoteGroupID, v))
}

// RemoteGroupIDGTE applies the GTE predicate on the "remote_group_id" field.
func RemoteGroupIDGTE(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldRemoteGroupID, v))
}

// RemoteGroupIDLT applies the LT predicate on the "remote_group_id" field.
func RemoteGroupIDLT(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldRemoteGroupID, v))
}

// RemoteGroupIDLTE applies the LTE predicate on the "remote_group_id" field.
func RemoteGroupIDLTE(v int64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldRemoteGroupID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldPlatform, v))
}

// SubscriptionTypeEQ applies the EQ predicate on the "subscription_type" field.
func SubscriptionTypeEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldSubscriptionType, v))
}

// SubscriptionTypeNEQ applies the NEQ predicate on the "subscription_type" field.
func SubscriptionTypeNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldSubscriptionType, v))
}

// SubscriptionTypeIn applies the In predicate on the "subscription_type" field.
func SubscriptionTypeIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldSubscriptionType, vs...))
}

// SubscriptionTypeNotIn applies the NotIn predicate on the "subscription_type" field.
func SubscriptionTypeNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldSubscriptionType, vs...))
}

// SubscriptionTypeGT applies the GT predicate on the "subscription_type" field.
func SubscriptionTypeGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldSubscriptionType, v))
}

// SubscriptionTypeGTE applies the GTE predicate on the "subscription_type" field.
func SubscriptionTypeGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldSubscriptionType, v))
}

// SubscriptionTypeLT applies the LT predicate on the "subscription_type" field.
func SubscriptionTypeLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldSubscriptionType, v))
}

// SubscriptionTypeLTE applies the LTE predicate on the "subscription_type" field.
func SubscriptionTypeLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldSubscriptionType, v))
}

// SubscriptionTypeContains applies the Contains predicate on the "subscription_type" field.
func SubscriptionTypeContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldSubscriptionType, v))
}

// SubscriptionTypeHasPrefix applies the HasPrefix predicate on the "subscription_type" field.
func SubscriptionTypeHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldSubscriptionType, v))
}

// SubscriptionTypeHasSuffix applies the HasSuffix predicate on the "subscription_type" field.
func SubscriptionTypeHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldSubscriptionType, v))
}

// SubscriptionTypeEqualFold applies the EqualFold predicate on the "subscription_type" field.
func SubscriptionTypeEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldSubscriptionType, v))
}

// SubscriptionTypeContainsFold applies the ContainsFold predicate on the "subscription_type" field.
func SubscriptionTypeContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldSubscriptionType, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldRateMultiplier, v))
}

// EffectiveRateMultiplierEQ applies the EQ predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldEffectiveRateMultiplier, v))
}

// EffectiveRateMultiplierNEQ applies the NEQ predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldEffectiveRateMultiplier, v))
}

// EffectiveRateMultiplierIn applies the In predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldEffectiveRateMultiplier, vs...))
}

// EffectiveRateMultiplierNotIn applies the NotIn predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldEffectiveRateMultiplier, vs...))
}

// EffectiveRateMultiplierGT applies the GT predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldEffectiveRateMultiplier, v))
}

// EffectiveRateMultiplierGTE applies the GTE predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldEffectiveRateMultiplier, v))
}

// EffectiveRateMultiplierLT applies the LT predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldEffectiveRateMultiplier, v))
}

// EffectiveRateMultiplierLTE applies the LTE predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldEffectiveRateMultiplier, v))
}

// EffectiveRateMultiplierIsNil applies the IsNil predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierIsNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIsNull(FieldEffectiveRateMultiplier))
}

// EffectiveRateMultiplierNotNil applies the NotNil predicate on the "effective_rate_multiplier" field.
func EffectiveRateMultiplierNotNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotNull(FieldEffectiveRateMultiplier))
}

// PeakRateEnabledEQ applies the EQ predicate on the "peak_rate_enabled" field.
func PeakRateEnabledEQ(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakRateEnabled, v))
}

// PeakRateEnabledNEQ applies the NEQ predicate on the "peak_rate_enabled" field.
func PeakRateEnabledNEQ(v bool) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldPeakRateEnabled, v))
}

// PeakRateMultiplierEQ applies the EQ predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierNEQ applies the NEQ predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierIn applies the In predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldPeakRateMultiplier, vs...))
}

// PeakRateMultiplierNotIn applies the NotIn predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldPeakRateMultiplier, vs...))
}

// PeakRateMultiplierGT applies the GT predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierGTE applies the GTE predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierLT applies the LT predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierLTE applies the LTE predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierIsNil applies the IsNil predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierIsNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIsNull(FieldPeakRateMultiplier))
}

// PeakRateMultiplierNotNil applies the NotNil predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNotNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotNull(FieldPeakRateMultiplier))
}

// PeakStartEQ applies the EQ predicate on the "peak_start" field.
func PeakStartEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakStart, v))
}

// PeakStartNEQ applies the NEQ predicate on the "peak_start" field.
func PeakStartNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldPeakStart, v))
}

// PeakStartIn applies the In predicate on the "peak_start" field.
func PeakStartIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldPeakStart, vs...))
}

// PeakStartNotIn applies the NotIn predicate on the "peak_start" field.
func PeakStartNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldPeakStart, vs...))
}

// PeakStartGT applies the GT predicate on the "peak_start" field.
func PeakStartGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldPeakStart, v))
}

// PeakStartGTE applies the GTE predicate on the "peak_start" field.
func PeakStartGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldPeakStart, v))
}

// PeakStartLT applies the LT predicate on the "peak_start" field.
func PeakStartLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldPeakStart, v))
}

// PeakStartLTE applies the LTE predicate on the "peak_start" field.
func PeakStartLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldPeakStart, v))
}

// PeakStartContains applies the Contains predicate on the "peak_start" field.
func PeakStartContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldPeakStart, v))
}

// PeakStartHasPrefix applies the HasPrefix predicate on the "peak_start" field.
func PeakStartHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldPeakStart, v))
}

// PeakStartHasSuffix applies the HasSuffix predicate on the "peak_start" field.
func PeakStartHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldPeakStart, v))
}

// PeakStartEqualFold applies the EqualFold predicate on the "peak_start" field.
func PeakStartEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldPeakStart, v))
}

// PeakStartContainsFold applies the ContainsFold predicate on the "peak_start" field.
func PeakStartContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldPeakStart, v))
}

// PeakEndEQ applies the EQ predicate on the "peak_end" field.
func PeakEndEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldPeakEnd, v))
}

// PeakEndNEQ applies the NEQ predicate on the "peak_end" field.
func PeakEndNEQ(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldPeakEnd, v))
}

// PeakEndIn applies the In predicate on the "peak_end" field.
func PeakEndIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldPeakEnd, vs...))
}

// PeakEndNotIn applies the NotIn predicate on the "peak_end" field.
func PeakEndNotIn(vs ...string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldPeakEnd, vs...))
}

// PeakEndGT applies the GT predicate on the "peak_end" field.
func PeakEndGT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldPeakEnd, v))
}

// PeakEndGTE applies the GTE predicate on the "peak_end" field.
func PeakEndGTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldPeakEnd, v))
}

// PeakEndLT applies the LT predicate on the "peak_end" field.
func PeakEndLT(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldPeakEnd, v))
}

// PeakEndLTE applies the LTE predicate on the "peak_end" field.
func PeakEndLTE(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldPeakEnd, v))
}

// PeakEndContains applies the Contains predicate on the "peak_end" field.
func PeakEndContains(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContains(FieldPeakEnd, v))
}

// PeakEndHasPrefix applies the HasPrefix predicate on the "peak_end" field.
func PeakEndHasPrefix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasPrefix(FieldPeakEnd, v))
}

// PeakEndHasSuffix applies the HasSuffix predicate on the "peak_end" field.
func PeakEndHasSuffix(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldHasSuffix(FieldPeakEnd, v))
}

// PeakEndEqualFold applies the EqualFold predicate on the "peak_end" field.
func PeakEndEqualFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEqualFold(FieldPeakEnd, v))
}

// PeakEndContainsFold applies the ContainsFold predicate on the "peak_end" field.
func PeakEndContainsFold(v string) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldContainsFold(FieldPeakEnd, v))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIsNil applies the IsNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdIsNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIsNull(FieldDailyLimitUsd))
}

// DailyLimitUsdNotNil applies the NotNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotNull(FieldDailyLimitUsd))
}

// WeeklyLimitUsdEQ applies the EQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdNEQ applies the NEQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIn applies the In predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdNotIn applies the NotIn predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdGT applies the GT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdGTE applies the GTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLT applies the LT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLTE applies the LTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIsNil applies the IsNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIsNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIsNull(FieldWeeklyLimitUsd))
}

// WeeklyLimitUsdNotNil applies the NotNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotNull(FieldWeeklyLimitUsd))
}

// MonthlyLimitUsdEQ applies the EQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdNEQ applies the NEQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNEQ(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIn applies the In predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdNotIn applies the NotIn predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotIn(vs ...float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdGT applies the GT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdGTE applies the GTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLT applies the LT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLT(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLTE applies the LTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLTE(v float64) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIsNil applies the IsNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIsNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIsNull(FieldMonthlyLimitUsd))
}

// MonthlyLimitUsdNotNil applies the NotNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotNil() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotNull(FieldMonthlyLimitUsd))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.FieldLTE(FieldSyncedAt, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.UpstreamGroup {
	return predicate.UpstreamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.UpstreamProvider) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamGroup) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamGroup) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamGroup) predicate.UpstreamGroup {
	return predicate.UpstreamGroup(sql.NotPredicates(p))
}
